name: Specs & Lint

on:
  push:
    branches: [main]
  pull_request:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Crystal
        uses: crystal-lang/install-crystal@v1
      - name: Check formatting
        run: crystal tool format --check
  flatpak-builder:
    name: "Flatpak Builder"
    runs-on: ubuntu-latest
    needs: [ lint ]
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:gnome-48
      options: --privileged
    strategy:
      matrix:
        variant:
          - arch: x86_64
            runner: ubuntu-latest
          - arch: aarch64
            runner: ubuntu-24.04-arm
      # Don't fail the whole workflow if one architecture fails
      fail-fast: false
    runs-on: ${{ matrix.variant.runner }}
    steps:
    - uses: actions/checkout@v4
    - name: Validate AppStream
      run: appstreamcli validate ./data/dev.geopjr.Collision.metainfo.xml.in
    - uses: flatpak/flatpak-github-actions/flatpak-builder@v6
      with:
        bundle: "dev.geopjr.Collision.Devel.flatpak"
        run-tests: true
        manifest-path: "data/dev.geopjr.Collision.json"
        cache-key: flatpak-builder-${{ github.sha }}
        arch: ${{ matrix.variant.arch }}
