name: Specs & Lint

on: [push, pull_request]
jobs:
  ci:
    runs-on: ubuntu-latest
    container: ghcr.io/geopjr/crystal-gtk:latest
    steps:
      - uses: actions/checkout@v3
      - name: Shards install & Generate bindings
        run: make bindings
      - name: Spec
        run: crystal spec -Dpreview_mt --order random || exit 1
      - name: Check formatting
        run: crystal tool format --check
