name: Specs & Lint

on: [push, pull_request]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: crystal-lang/install-crystal@v1
        with:
          crystal: 1.2.1
      - name: Shards install
        run: shards install
      - name: Spec
        run: crystal spec || exit 1
      - name: Check formatting
        run: crystal tool format --check
